fix possible IAE if NaN values are in sorted set
In some cases the sort would fail with:

```
IllegalArgumentException: Comparison method violates its general contract!
```

This was caused by having a mix of NaNs in the set of
values being sorted. This change switches to use
`Double.compare` which takes NaN values into account.