reduce use of guava
Removes some of the simple uses of guava.

Not sure why, but something about the
TimeSeriesBuffer class triggers a
ClassNotFoundException with the
equalsverifier library:

```
[info]   Cause: java.lang.NoClassDefFoundError: nl/jqno/equalsverifier/internal/cglib/proxy/Factory
[info]   at java.lang.ClassLoader.defineClass1(Native Method)
[info]   at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[info]   at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.lang.reflect.Method.invoke(Method.java:483)
[info]   at nl.jqno.equalsverifier.internal.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:384)
[info]   at nl.jqno.equalsverifier.internal.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:219)
[info]   at nl.jqno.equalsverifier.internal.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
[info]   at nl.jqno.equalsverifier.internal.cglib.proxy.Enhancer.createClass(Enhancer.java:317)
[info]   at nl.jqno.equalsverifier.util.Instantiator.createDynamicSubclass(Instantiator.java:104)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: nl.jqno.equalsverifier.internal.cglib.proxy.Factory
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[info]   at java.lang.ClassLoader.defineClass1(Native Method)
[info]   at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[info]   at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   ...
```

Current workaround is to set `fork in Test := true`
for the sbt build.