fix build settings for 2.13 to use `-release 8`
Before it was looking specifically for version 12. For now
we still need to be able to run on jdk8+. The specific issue
encountered was:

```
java.lang.NoSuchMethodError: java.nio.CharBuffer.clear()Ljava/nio/CharBuffer;
   at com.netflix.atlas.core.model.TaggedItem$.writePair(TaggedItem.scala:59)
   at com.netflix.atlas.core.model.TaggedItem$.computeId(TaggedItem.scala:105)
   at com.netflix.atlas.core.model.TimeSeries$.<clinit>(TimeSeries.scala:22)
   at com.netflix.atlas.core.model.EvalContext.<init>(EvalContext.scala:32)
   at com.netflix.atlas.druid.DruidDatabaseActorSuite.<init>(DruidDatabaseActorSuite.scala:259)
   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
   at java.lang.Class.newInstance(Class.java:442)
```