treat empty title and ylabel params as not set
If the URI contains title or ylabel values that are set
to an empty string it is currently returning an error during
rendering:

```
IllegalArgumentException: Can't add attribute to 0-length text.
```

With this change an empty string for those values will be
the same as not having them set.