set target to jvm-1.8
There are several uses of java 8 APIs and targeting
java 8 makes the error message a little more clear
(or at least easier to search for) if running on an
older jvm. Prior error when running on 1.7:

```
$ java -jar atlas-1.4.1-standalone.jar
[main] INFO com.netflix.atlas.webapi.Main$$anon$1 - starting atlas on port 7101
[main] WARN com.netflix.spectator.api.Spectator - no registry impl found in classpath, using default
[atlas-akka.actor.default-dispatcher-2] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.netflix.atlas.webapi.ApiSettings$.newDbInstance(ApiSettings.scala:33)
	at com.netflix.atlas.webapi.Main$$anon$1.configure(Main.scala:29)
	at com.netflix.atlas.akka.WebServer.start(WebServer.scala:37)
	at com.netflix.atlas.webapi.Main$.main(Main.scala:33)
	at com.netflix.atlas.webapi.Main.main(Main.scala)
	... 6 more
Caused by: java.lang.NoClassDefFoundError: java/time/ZoneId
	at com.netflix.atlas.core.db.StaticDatabase.<init>(StaticDatabase.scala:33)
	... 15 more
Caused by: java.lang.ClassNotFoundException: java.time.ZoneId
	at com.simontuffs.onejar.JarClassLoader.findClass(JarClassLoader.java:713)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at com.simontuffs.onejar.JarClassLoader.loadClass(JarClassLoader.java:630)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 16 more
```

Current error when running on 1.7:

```
$ java -jar atlas-1.4.1-standalone.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/netflix/atlas/webapi/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at com.simontuffs.onejar.JarClassLoader.defineClass(JarClassLoader.java:803)
	at com.simontuffs.onejar.JarClassLoader.findClass(JarClassLoader.java:710)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at com.simontuffs.onejar.JarClassLoader.loadClass(JarClassLoader.java:630)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.simontuffs.onejar.Boot.run(Boot.java:334)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
```