use jdk8 for building the scala 2.11 artifacts
Since 2.11 doesn't support the `--release` option, building
on a newer version can lead to errors when running on jdk8.
Specifically the return type of some methods changed in jdk9+.

This should fix errors like:

```
Cause: java.lang.NoSuchMethodError: java.nio.CharBuffer.clear()Ljava/nio/CharBuffer;
  at com.netflix.atlas.core.model.TaggedItem$.writePair(TaggedItem.scala:59)
  at com.netflix.atlas.core.model.TaggedItem$.computeId(TaggedItem.scala:105)
```