fix links for expressions in wiki
Updates the word links for graph expressions to point
to the actual page. See [examples](https://github.com/Netflix/atlas/wiki/Single-Line).
The make it easier to generate a link with just the name
the [reference page](https://github.com/Netflix/atlas/wiki/Stack-Language-Reference)
was updated with an alphabetical list showing the variants.

Not addressed in this PR, but updating the jmh plugin to
0.1.15 breaks the publish-wiki task in the makefile. The
first problem is the working directory changes to be the
atlas-wiki project dir. Fixing that leads to strange exception
when trying to run:

```
info] [init] error: error while loading Object, Missing dependency 'object scala in compiler mirror', required by /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/rt.jar(java/lang/Object.class)
[info]
[info] Failed to initialize compiler: object scala in compiler mirror not found.
[info] ** Note that as of 2.8 scala does not assume use of the java classpath.
[info] ** For the old behavior pass -usejavacp to scala, or if using a Settings
[info] ** object programmatically, settings.usejavacp.value = true.
[error] Exception in thread "main" scala.reflect.internal.MissingRequirementError: object scala in compiler mirror not found.
[error] 	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
[error] 	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
[error] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
[error] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
[error] 	at scala.reflect.internal.Mirrors$RootsBase.getPackage(Mirrors.scala:173)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackage$lzycompute(Definitions.scala:161)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackage(Definitions.scala:161)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackageClass$lzycompute(Definitions.scala:162)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.ScalaPackageClass(Definitions.scala:162)
[error] 	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1392)
[error] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1216)
[error] 	at scala.tools.nsc.interpreter.IMain.compileSourcesKeepingRun(IMain.scala:422)
[error] 	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compileAndSaveRun(IMain.scala:841)
[error] 	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:800)
[error] 	at scala.tools.nsc.interpreter.IMain.bind(IMain.scala:664)
[error] 	at scala.tools.nsc.interpreter.IMain.bind(IMain.scala:701)
[error] 	at scala.tools.nsc.interpreter.IMain$$anon$2.put(IMain.scala:1035)
[error] 	at com.netflix.atlas.wiki.Main$.eval(Main.scala:91)
[error] 	at com.netflix.atlas.wiki.Main$.process(Main.scala:106)
[error] 	at com.netflix.atlas.wiki.Main$.com$netflix$atlas$wiki$Main$$processTemplate(Main.scala:121)
[error] 	at com.netflix.atlas.wiki.Main$$anonfun$com$netflix$atlas$wiki$Main$$copy$2.apply(Main.scala:159)
[error] 	at com.netflix.atlas.wiki.Main$$anonfun$com$netflix$atlas$wiki$Main$$copy$2.apply(Main.scala:157)
[error] 	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[error] 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
[error] 	at com.netflix.atlas.wiki.Main$.com$netflix$atlas$wiki$Main$$copy(Main.scala:157)
[error] 	at com.netflix.atlas.wiki.Main$.main(Main.scala:272)
[error] 	at com.netflix.atlas.wiki.Main.main(Main.scala)
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
```